# Generated by Django 2.2.5 on 2019-09-20 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180406_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='caption',
            field=models.TextField(default=uuid.uuid4, max_length=200),
        ),
    ]
