# Generated by Django 2.2.5 on 2019-09-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_albumimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimage',
            name='caption',
        ),
    ]
