# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-29 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_albumimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='caption',
            field=models.TextField(default=uuid.uuid4, max_length=200),
        ),
    ]
