# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-29 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_albumimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='caption',
            field=models.TextField(default=b'', max_length=200),
        ),
    ]
