# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-29 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190929_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='caption',
            field=models.TextField(max_length=200),
        ),
    ]
