# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-30 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190930_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimage',
            name='album',
        ),
        migrations.DeleteModel(
            name='homeImage',
        ),
    ]
