# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-02 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191002_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='caption',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='comment',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='place',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
