# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-07 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191003_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=b'albums')),
                ('alt', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, max_length=250)),
            ],
        ),
    ]
